apiVersion: v1
kind: Service
metadata:
  name: musixtream-frontend
  namespace: musixtream
spec:
  selector:
    app: musixtream
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  type: LoadBalancer
  