apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: musixtream
  name: musixtream
---
apiVersion: v1
kind: Service
metadata:
  name: musixtream
  namespace: musixtream
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: musixtream
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: musixtream
  name: musixtream
  namespace: musixtream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musixtream
  template:
    metadata:
      labels:
        app: musixtream
      name: musixtream
    spec:
      automountServiceAccountToken: false
      containers:
      - image: dudesjef/musixtream-frontend
        imagePullPolicy: IfNotPresent
        name: musixtream
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: 200Mi
      restartPolicy: Always