apiVersion: v1
kind: Service
metadata:
  name: musixtream-frontend-service
  namespace: musixtream
spec:
  type: LoadBalancer
  selector:
    app: musixtream
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000