apiVersion: v1
kind: Service
metadata:
  name: musixtream-frontend
  namespace: musixtream
spec:
  selector:
    app: musixtream
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  